import { Inter } from "next/font/google";
import "./globals.css";
import GlobalsProvider from "./contexts/Globals";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QuickFood",
  description: "Generated by create next app",
  icon: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalsProvider>
          <div className="overflow-hidden">
            <NavBar />
            {children}
          </div>
        </GlobalsProvider>
      </body>
    </html>
  );
}
